DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users(
  user_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone_number BIGINT NOT NULL,
  carrier TEXT NOT NULL,
  password TEXT NOT NULL  
);
